[build]
functions="functions"
publish="dist"
[[redirects]]
from ="/register"
to="/.netlify/functions/addingexpress/"
status = 200
force = true
[[redirects]]
from ="/register/*"
to="/.netlify/functions/addingexpress/"
status = 200
force = true